INSERT INTO kodok (kodcsop,kod,szoveg) VALUES
('JOGI','I','Végleges jogi eredmény'),
('JOGI','N','Az eredmény még nem végleges jogi'),
('ALLTIP','1','Törzsadatok'),
('ALLTIP','2','Napközbeni jelentések adatai'),
('ALLTIP','3','Szavazatösszesítési adatok'),
('MANDO','0','Országos listás mandátumosztás még nem történt meg'),
('MANDO','1','Országos listás mandátumosztás megtörtént'),
('SZEM','0','Mandátumok személyhez rendelése még nem történt meg'),
('SZEM','1','Mandátumok személyhez rendelése megtörtént'),
('TELTIP','1','Fővárosi kerület'),
('TELTIP','2','Megyei jogú város'),
('TELTIP','3','Város'),
('TELTIP','4','Község'),
('SZKTIP','1','Normál szavazókör'),
('SZKTIP','2','Telep.szintű lakosok és átjelentkezettek szavazására kijelölt'),
('SZKTIP','3','A külképv.és átjelent.szavazók szavazatainak megszámlálására kijelölt'),
('SZKTIP','4','A levélben szavazás eredményét jelző technikai szavazókör'),
('SZAVLA','0','Szavazólapon nem szerepel'),
('SZAVLA','1','Szerepel a szavazólapon'),
('SZAVLA','2','Szerepel a szavazólapon, de érvénytelenül'),
('LTIP','O','Önálló lista'),
('LTIP','K','Közös lista'),
('LTIP','N','Nemzetiségi lista'),
('NAPSZINT','1','Egyéni választókerületi adatok'),
('NAPSZINT','2','Települési szintű adatok'),
('NAPSZINT','3','Szavazóköri szintű elemi adatok'),
('NAPSZINT','4','Megyei, fővárosi összesített adatok'),
('NAPSZINT','5','Országos szintű összesített adatok'),
('SZAVSZINT','1','Egyéni választókerületi adatok'),
('SZAVSZINT','4','Megyei, fővárosi összesített adatok'),
('SZAVSZINT','51','Országosan összesített listás szavazatok (Mo. + külképviselet + levélben)'),
('SZAVSZINT','52','Országosan összesített listás szavazatok (Mo. + külképviselet)'),
('SZAVSZINT','53','Listás szavazatok (levélben)'),
('JELENT','I','Szavazóköri szintű napközbeni jelentés érkezett'),
('JELENT','N','Szavazóköri szintű napközbeni jelentés nem érkezett'),
('VALTIP','J','Egyéni választókerületi választás'),
('VALTIP','L','Listás választás'),
('FORR','0','Előzetes adat'),
('FORR','1','Jegyzőkönyvi adat'),
('FORR','4','Megsemmisített jegyzőkönyvi adat'),
('EREDM','0','Nincs értékelhető adat'),
('EREDM','1','Eredményes választás'),
('EREDM','2','Eredménytelen választás'),
('HATAR','0','Nem történt mandátum számítás'),
('HATAR','1','Mandátumot kaphat'),
('HATAR','2','Mandátumot nem kaphat'),
('MTIP','1','Egyéni választókerületi mandátum'),
('MTIP','2','Országos listás mandátum'),
('MTIP','3','Nemzetiségi listás mandátum'),
('PARTNEMZ','P','Párt (egyéni jelöltet és pártlistát állíthat)'),
('PARTNEMZ','N','Országos Nemzetiségi Önkormányzat (nemzetiségi listát állíthat)'),
('NEMZ','1','bolgár'),
('NEMZ','2','görög'),
('NEMZ','3','horvát'),
('NEMZ','4','lengyel'),
('NEMZ','5','német'),
('NEMZ','6','örmény'),
('NEMZ','7','roma'),
('NEMZ','8','román'),
('NEMZ','9','ruszin'),
('NEMZ','10','szerb'),
('NEMZ','11','szlovák'),
('NEMZ','12','szlovén'),
('NEMZ','13','ukrán'),
('UNEVSZ','1','Csak az első utónév jelenítendő meg'),
('UNEVSZ','2','Csak a második utónév jelenítendő meg'),
('DRJEL','I','Dr. jelző megjelenítendő'),
('DRJEL','N','Dr. jelző nem jelenítendő meg'),
('ALLAPOT','0','Bejelentve'),
('ALLAPOT','1','Nyilvántartásba véve'),
('ALLAPOT','2','Nyilvántartásba vétel elutasítva (nem jogerős)'),
('ALLAPOT','3','Nyilvántartásból törölve'),
('ALLAPOT','4','Nyilvántartásba vétel elutasítva'),
('ALLAPOT','5','Nyilvántartásba véve (nem jogerős)'),
('ALLAPOT','6','Nyilvántartásból törölve (nem jogerős)'),
('ALLAPOT','7','Visszalépett/visszavonva'),
('ALLAPOT','8','Elhunyt'),
('ALLAPOT','9','Választójoga megszűnt'),
('ALLAPOT','11','Jelölő szervezete törölve'),
('ALLAPOT','12','Ajánlóíveket átvette'),
('ALLAPOT','13','Ajánlóíveket nem adta le határidőben'),
('ALLAPOT','14','Ajánlóíveket leadta határidőben'),
('ALLAPOT','15','Nem kíván indulni'),
('ALLAPOT','16','Ajánlóívet igényelt'),
('ALLAPOT','17','Ajánlóív igénylése elutasítva'),
('ALLAPOT','18','Lista törölve (nem jogerős)'),
('ALLAPOT','19','Lista törölve');
